Add CM/ECF research page
freelawproject/free.law pull request #183
Opened 2024-05-06 11:58 UTC by cmaczo

- Adding an “Electronic Filing and Case Management Research” page, which contains:
    - Links to relevant blog posts
    - Links to FOIA’ed documents
- Linking that page from the footer

2024-05-06 22:01 UTC, mlissner requested changes
I think it'd be a bit better if this is just a resources page, with less explanation, sort of like this one: 

https://free.law/non-profit-documents

We could then do a brief blog post (like two paragraphs, max three)  saying what we're up to and linking to it, and we could just post the latest contracts as we get them.

What do you think?

2024-05-06 22:01 UTC, mlissner commented on posts/projects/filing-and-case-management.mdx
> +## Existing state contracts for related systems
Per my larger comment, I think the easiest thing is to just remove this part.

2024-05-06 22:01 UTC, mlissner commented on components/footers.js
> +            <FooterLink href="/projects/filing-and-case-management/">Filing and Case Management System Research</FooterLink>
Could we get away with this, if we remove the blog links:

```suggestion
            <FooterLink href="/projects/filing-and-case-management/">Court Contracts</FooterLink>
```

2024-05-07 17:11 UTC, mlissner commented
Will you let me know when this is ready for another review?

2024-05-07 17:12 UTC, cmaczo commented
@mlissner I think it's ready now.

2024-05-07 20:19 UTC, mlissner approved these changes

2024-05-07 20:19 UTC, merged

2024-05-07 20:20 UTC, mlissner commented
Cool. Will you have time to do a short post about this saying:

 - What we did
 - Why we did it
 - What we've got so far
 - What we'll do in the future as we get things

?

2024-05-08 21:14 UTC, cmaczo commented
Yes, I will try!